language: objective-c
osx_image: xcode61
before_install:
  - brew update
  - brew install pcre
  - brew install icu4c
install:
  - mkdir -p $(brew --repo)/Library/Taps/homebrew
  - ln -s $PWD $(brew --repo)/Library/Taps/homebrew/homebrew-nginx
  - brew tap --repair
  - brew tap
env:
  - MODULE=""
  - MODULE="spdy"
  - MODULE="geoip"
  - MODULE="lua-module"
  - MODULE="headers-more-module"
  - MODULE="xsltproc-module"
script:
  - brew audit nginx-full
  - brew install -v nginx-full --with-$MODULE
matrix:
  fast_finish: true
